### ISSUE TITLE
new COSIA data added

### ISSUE THREAD

**Issue by s-martiz** [IGNF/FLAIR-2#4]
Dear all
As part of a research project, I am very interested in the COSIA project. 
My question is simple: are there any plans to add new results soon? I regularly check this address, which doesn't seem to have been updated for some time https://cosia.ign.fr/info#export
I am particularly interested in the Charente-Maritime department (17). 
Kind regards and congratulations on your work.

**Comment by agarioud** [comment]
Dear @simonmarti1992 , we anticipate that the entire France will be covered with the first version of the CoSIA product by the first semester of 2024. For additional information, please don't hesitate to reach out through the contact email available on the website you mentioned

**Comment by s-martiz** [comment]
Dear @agarioud 
I wanted to inquire if there is now an api available to download the data directly. It would be highly beneficial for streamlining my data acquisition process.
Best regards,
Simon

**Comment by agarioud** [comment]
Hello @simonmarti1992 
Are you referring to the CoSIA product or the FLAIR data ? 
For CoSIA unfortunately there is no API for now, you'll have to manually download through cosia.ign.fr. I can raise the need for an API.
Regarding FLAIR, the dataset is hosted on HuggingFace, allowing one to download the data with the datasets or huggingface_hub python libraries. 
Best,

**Comment by s-martiz** [comment]
@agarioud 
I am indeed referring to the COSIA product. For now, I am downloading it manually, but this complicates my process as I have to find the intersection between my area of interest (often small) and the entire dataset of the department.
Best

**Comment by s-martiz** [comment]
Could you please indicate how each tile is named >`D017_2021_370_6530_vecto.gpkg`? 
This information would likely help me speed up my "intersection search".

**Comment by agarioud** [comment]
D017 : corresponds to the département 
2021 : to the year of aerial imagery acquisition
370_6530 : first 3 and 4 numbers of longitude/latitude in EPSG:2154 (this seems to roughly correspond to near l'Ile d'Oléron)

indeed we don't have a 'on-the-fly' area of interest cropping tool for CoSIA. I'll raise the need.
